### ISSUE TITLE
能否添加Orange Pi Zero Plus？

### ISSUE THREAD

**Issue by skyrockgz** [Gabrielxzx/Actions-OpenWrt#3]
搜索了一圈，您的这个编译的固件是最接近我的Orange Pi Zero Plus的，但两者芯片不同，能否新增这个型号的编译？谢谢

**Comment by Gabrielxzx** [comment]
理论上和我编译的nanopi neo2应该是通用的，你可以先试试neo2的固件。如果不行我在加入zero plus，但是我没有设备测试

https://github.com/Gabrielxzx/Actions-OpenWrt/actions/workflows/NanoPi-neo2.yml

**Comment by Gabrielxzx** [comment]
> 搜索了一圈，您的这个编译的固件是最接近我的Orange Pi Zero Plus的，但两者芯片不同，能否新增这个型号的编译？谢谢

理论上和我编译的nanopi neo2应该是通用的，你可以先试试neo2的固件。如果不行我在加入zero plus，但是我没有设备测试

https://github.com/Gabrielxzx/Actions-OpenWrt/actions/workflows/NanoPi-neo2.yml
