### ISSUE TITLE
XR819无法驱动

### ISSUE THREAD

**Issue by david-bowiegxw** [Gabrielxzx/Actions-OpenWrt#4]
已经有一些解决方案了 希望编译到固件里

**Comment by Gabrielxzx** [comment]
有链接吗？我去看下

> 已经有一些解决方案了 希望编译到固件里

**Comment by david-bowiegxw** [comment]
https://github.com/fifteenhex/xradio
https://github.com/dbeinder/xradio/tree/karabek_rebase
https://github.com/melsem/openwrt-lede_xradio-xr819_soc-audio
https://github.com/katyo/xr819
Armbian对XR819的支持也很好

**Comment by Benjamin23333** [comment]
> 有链接吗？我去看下
> 
> > 已经有一些解决方案了 希望编译到固件里

![image](https://user-images.githubusercontent.com/54323063/146757816-d773ca5b-820d-4cd4-9b94-4450040cfd1c.png)
argon主题的包名换了，您可能需要改一下配置文件😇

**Comment by Gabrielxzx** [comment]
> > 有链接吗？我去看下
> > > 已经有一些解决方案了 希望编译到固件里
> 
> ![image](https://user-images.githubusercontent.com/54323063/146757816-d773ca5b-820d-4cd4-9b94-4450040cfd1c.png) argon主题的包名换了，您可能需要改一下配置文件😇

打工人平时只想睡觉，周六更新config文件，现在的报错周六一起更新。

**Comment by Benjamin23333** [comment]
> > > 有链接吗？我去看下
> > > > 已经有一些解决方案了 希望编译到固件里
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54323063/146757816-d773ca5b-820d-4cd4-9b94-4450040cfd1c.png) argon主题的包名换了，您可能需要改一下配置文件😇
> 
> 打工人平时只想睡觉，周六更新config文件，现在的报错周六一起更新。

这样啊，抱歉打扰到您

**Comment by Gabrielxzx** [comment]
> 



> > > > 有链接吗？我去看下
> > > > > 已经有一些解决方案了 希望编译到固件里
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/54323063/146757816-d773ca5b-820d-4cd4-9b94-4450040cfd1c.png) argon主题的包名换了，您可能需要改一下配置文件😇
> > 
> > 
> > 打工人平时只想睡觉，周六更新config文件，现在的报错周六一起更新。
> 
> 这样啊，抱歉打扰到您

看了下，老竭力又把主题名字改回去了，另外XR819的驱动我搞不定，一定是我太菜了

**Comment by Benjamin23333** [comment]
> > 
> 
> > > > > 有链接吗？我去看下
> > > > > > 已经有一些解决方案了 希望编译到固件里
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/54323063/146757816-d773ca5b-820d-4cd4-9b94-4450040cfd1c.png) argon主题的包名换了，您可能需要改一下配置文件😇
> > > 
> > > 
> > > 打工人平时只想睡觉，周六更新config文件，现在的报错周六一起更新。
> > 
> > 
> > 这样啊，抱歉打扰到您
> 
> 看了下，老竭力又把主题名字改回去了，另外XR819的驱动我搞不定，一定是我太菜了

嗯，我之前也看到了，但是看到您之前说周六再说，我就想周六再告诉您，既然您现在已经知道了，那就没事了🤣
